### ISSUE TITLE
quite poor quality

### ISSUE THREAD

**Issue by chuck-ma** [hiteshK03/Pix2Gif#2]
![image](https://github.com/hiteshK03/Pix2Gif/assets/74402255/0124e008-c8aa-4a9c-9618-f0804f902e39)

I use 1024 * 576 resolution pictures. The generated animation is very blurry

**Comment by jwyang** [comment]
Hi, @chuck-ma , thanks for your interest, now the model only produces low resolution images.

**Comment by satwikug25** [comment]
Hi @chuck-ma @jwyang , how did you run the model, I am unable to locate the ckpt file.
